version: '3'
services:
  app-nginx:
    container_name: app-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  app-mysql:
    container_name: app-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: cs544
      MYSQL_ROOT_PASSWORD: lionos
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  app:
    restart: always
    build: ./
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - app-mysql