server:
  port: 8085

spring:    
  application:
    name: tm
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:postgresql://ec2-52-201-55-4.compute-1.amazonaws.com:5432/dbrgiocc8ks13a
    username: exjpqiimmspqzn
    password: 6ac47b8c60b3d7024543265421a03a36432f20acca51aa097c2670a4674e3e4d
    platform: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ea544.team6@gmail.com
    password: EA544_team6
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

sync-job:
  delay:
    milliseconds:
      fixed: 5000
      initial: 5000
