server:
  port: 8085
spring:    
  application:
    name: tm
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:mysql://localhost/cs544?serverTimezone=UTC
    username: root
    password: amirspring
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    format-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ea544.team6@gmail.com
    password: EA544_team6
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

sync-job:
  delay:
    milliseconds:
      fixed: 5000
      initial: 5000
