server:
  port: 8081

spring:    
  application:
    name: tm
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:mysql://localhost/team6?serverTimezone=UTC
    username: team6
    password: team6
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: cs544.team6@gmail.com
    password: CS544_team6
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

sync-job:
  delay:
    milliseconds:
      fixed: 5000
      initial: 5000

schedule:
  notification:
    reminder:
      minutes: 15
